name: 'Bump tag based on PR branch name / title'
description: 'Bump tag based on PR branch name / title'
author: 'KoaLaYT'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
# inputs:
# milliseconds:
#   description: 'Your input description here'
#   required: true
#   default: '1000'

# Define your outputs here.
outputs:
  new_tag:
    description: 'new tag'

runs:
  using: node20
  main: dist/index.js
